site_name: Hair-Shifter documentation
theme:
  name: readthedocs

nav:
  - Contributions:
    - Structure: structure.md
    - Git version control: git.md
    - Testing: test.md
    - Dependency Management: dependencies.md
  - Models:
    - Motion Extractor (E_M): motion_extractor.md
    - Appeareance Extractor (E_H & E_C): appearance_feature_extractor.md
    - Warping Module (W): warping_network.md
    - Spade & SpadeResnet: spade.md
    - MSG Spade Decoder (G): msg_spade_decoder.md
  - Loaders:
    - Registry: registry.md
    - Loader: loader.md
    - Downloader: downloader.md
  - Losses:
    - Perceptual loss: perceptual_loss.md
    - Adversarial loss: adversarial_loss.md
    - Local loss: local_loss.md
