training:
  epoch_num: 100
  batch_size: 4
  mini_batch_size: 2
  discriminator:
    learn_rate: 2e-4
    betas: [0.5, 0.999]
  generator:
    learn_rate: 2e-5
    betas: [0.5, 0.999]
  loss:
    adv_rate: 1
    rec_rate: 1
    p_rate: 1
    h_rate: 1
    f_rate: 1
  save_dir: './checkpoints/'
  epochs_till_save: 10
  steps_till_save: 1000

dataset:
  dataset_dir: './assets/dataset'
  num_workers: 1
  device: -1

generation:
  driving_dir: './src/manager/assets/driving_images/'
  reference_dir: './src/manager/assets/reference_images/'
  cache_path: './src/manager/assets/cache.txt'

inference:
  video_path: './assets/test_images/phuc.mp4'
  reference_path: './assets/test_images/ken.png'
  checkpoint_path: './checkpoints/test.pt'
  output_path: './assets/test.avi'
  batch_size: 2
  frame_size: 512
  fps: 30
