training:
  epoch_num: 100
  batch_size: 4
  mini_batch_size: 2
  discriminator:
    learn_rate: 2e-4
    betas: [0.5, 0.999]
  generator:
    learn_rate: 2e-5
    betas: [0.5, 0.999]
  loss:
    adv_rate: 1
    rec_rate: 1
    p_rate: 1
    h_rate: 1
    f_rate: 1
  save_dir: './checkpoints/'
  epochs_till_save: 10
  steps_till_save: 1000

dataset:
    reference_dir: './assets/reference_images/'
    driving_dir: './assets/driving_images/'
    generated_dir: './assets/generated_images/'
    validated_cache_path: './src/manager/cache.txt'
    num_workers: 1
    device: -1
