training:
  epoch_num: 100
  batch_size: 4
  discriminator:
    learn_rate: 2e-4
    betas: [0.5, 0.999]
  generator:
    learn_rate: 2e-5
    betas: [0.5, 0.999]
  loss:
    adv_rate: 1
    rec_rate: 1
    p_rate: 1
    h_rate: 1
    f_rate: 1
